export const RECEBIMENTO_EVENT = {
  PRE_RECEBIMENTO_CRIADO: 'PRE_RECEBIMENTO_CRIADO',
  PRE_RECEBIMENTO_ATUALIZADO: 'PRE_RECEBIMENTO_ATUALIZADO',
  PRE_RECEBIMENTO_CANCELADO: 'PRE_RECEBIMENTO_CANCELADO',
  CONFERENCIA_LIBERADA: 'CONFERENCIA_LIBERADA',
  RECEBIMENTO_INICIADO: 'RECEBIMENTO_INICIADO',
  RECEBIMENTO_IMPEDIDO: 'RECEBIMENTO_IMPEDIDO',
  CONFERENCIA_RETOMADA: 'CONFERENCIA_RETOMADA',
  ITEM_CONFERIDO: 'ITEM_CONFERIDO',
  DIVERGENCIA_IDENTIFICADA: 'DIVERGENCIA_IDENTIFICADA',
  RECEBIMENTO_CONFERIDO: 'RECEBIMENTO_CONFERIDO',
  CONFERENCIA_REABERTA: 'CONFERENCIA_REABERTA',
  RECEBIMENTO_FINALIZADO: 'RECEBIMENTO_FINALIZADO',
  RECEBIMENTO_CANCELADO: 'RECEBIMENTO_CANCELADO',
  TAREFA_ARMAZENAGEM_GERADA: 'TAREFA_ARMAZENAGEM_GERADA',
} as const;

export type RecebimentoEventType =
  (typeof RECEBIMENTO_EVENT)[keyof typeof RECEBIMENTO_EVENT];

export type RecebimentoDomainEvent = {
  type: RecebimentoEventType;
  preRecebimentoId: string;
  recebimentoId?: string;
  unidadeId: string;
  userId: number | null;
  metadata?: Record<string, unknown>;
};
