/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AlterarSenhaRouteImport } from './routes/alterar-senha'
import { Route as RecebimentoRcRouteRouteImport } from './routes/recebimento-rc/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RecebimentoRcIndexRouteImport } from './routes/recebimento-rc/index'
import { Route as PesoVariavelIndexRouteImport } from './routes/peso-variavel/index'
import { Route as PassagemBastaoIndexRouteImport } from './routes/passagem-bastao/index'
import { Route as ManobraIndexRouteImport } from './routes/manobra/index'
import { Route as RecebimentoRcSyncRouteImport } from './routes/recebimento-rc/sync'
import { Route as RecebimentoRcIdRouteImport } from './routes/recebimento-rc/$id'
import { Route as RastreioTokenRouteImport } from './routes/rastreio/$token'
import { Route as PesoVariavelIdRouteImport } from './routes/peso-variavel/$id'
import { Route as PassagemBastaoResumoRouteImport } from './routes/passagem-bastao/resumo'
import { Route as RecebimentoRcIdIndexRouteImport } from './routes/recebimento-rc/$id.index'
import { Route as PesoVariavelIdIndexRouteImport } from './routes/peso-variavel/$id.index'
import { Route as RecebimentoRcIdResumoRouteImport } from './routes/recebimento-rc/$id.resumo'
import { Route as RecebimentoRcIdItensRouteImport } from './routes/recebimento-rc/$id.itens'
import { Route as RecebimentoRcIdChecklistRouteImport } from './routes/recebimento-rc/$id.checklist'
import { Route as RecebimentoRcIdAvariasRouteImport } from './routes/recebimento-rc/$id.avarias'
import { Route as PesoVariavelIdResumoRouteImport } from './routes/peso-variavel/$id.resumo'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AlterarSenhaRoute = AlterarSenhaRouteImport.update({
  id: '/alterar-senha',
  path: '/alterar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const RecebimentoRcRouteRoute = RecebimentoRcRouteRouteImport.update({
  id: '/recebimento-rc',
  path: '/recebimento-rc',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecebimentoRcIndexRoute = RecebimentoRcIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RecebimentoRcRouteRoute,
} as any)
const PesoVariavelIndexRoute = PesoVariavelIndexRouteImport.update({
  id: '/peso-variavel/',
  path: '/peso-variavel/',
  getParentRoute: () => rootRouteImport,
} as any)
const PassagemBastaoIndexRoute = PassagemBastaoIndexRouteImport.update({
  id: '/passagem-bastao/',
  path: '/passagem-bastao/',
  getParentRoute: () => rootRouteImport,
} as any)
const ManobraIndexRoute = ManobraIndexRouteImport.update({
  id: '/manobra/',
  path: '/manobra/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecebimentoRcSyncRoute = RecebimentoRcSyncRouteImport.update({
  id: '/sync',
  path: '/sync',
  getParentRoute: () => RecebimentoRcRouteRoute,
} as any)
const RecebimentoRcIdRoute = RecebimentoRcIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => RecebimentoRcRouteRoute,
} as any)
const RastreioTokenRoute = RastreioTokenRouteImport.update({
  id: '/rastreio/$token',
  path: '/rastreio/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const PesoVariavelIdRoute = PesoVariavelIdRouteImport.update({
  id: '/peso-variavel/$id',
  path: '/peso-variavel/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PassagemBastaoResumoRoute = PassagemBastaoResumoRouteImport.update({
  id: '/passagem-bastao/resumo',
  path: '/passagem-bastao/resumo',
  getParentRoute: () => rootRouteImport,
} as any)
const RecebimentoRcIdIndexRoute = RecebimentoRcIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RecebimentoRcIdRoute,
} as any)
const PesoVariavelIdIndexRoute = PesoVariavelIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PesoVariavelIdRoute,
} as any)
const RecebimentoRcIdResumoRoute = RecebimentoRcIdResumoRouteImport.update({
  id: '/resumo',
  path: '/resumo',
  getParentRoute: () => RecebimentoRcIdRoute,
} as any)
const RecebimentoRcIdItensRoute = RecebimentoRcIdItensRouteImport.update({
  id: '/itens',
  path: '/itens',
  getParentRoute: () => RecebimentoRcIdRoute,
} as any)
const RecebimentoRcIdChecklistRoute =
  RecebimentoRcIdChecklistRouteImport.update({
    id: '/checklist',
    path: '/checklist',
    getParentRoute: () => RecebimentoRcIdRoute,
  } as any)
const RecebimentoRcIdAvariasRoute = RecebimentoRcIdAvariasRouteImport.update({
  id: '/avarias',
  path: '/avarias',
  getParentRoute: () => RecebimentoRcIdRoute,
} as any)
const PesoVariavelIdResumoRoute = PesoVariavelIdResumoRouteImport.update({
  id: '/resumo',
  path: '/resumo',
  getParentRoute: () => PesoVariavelIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/recebimento-rc': typeof RecebimentoRcRouteRouteWithChildren
  '/alterar-senha': typeof AlterarSenhaRoute
  '/login': typeof LoginRoute
  '/passagem-bastao/resumo': typeof PassagemBastaoResumoRoute
  '/peso-variavel/$id': typeof PesoVariavelIdRouteWithChildren
  '/rastreio/$token': typeof RastreioTokenRoute
  '/recebimento-rc/$id': typeof RecebimentoRcIdRouteWithChildren
  '/recebimento-rc/sync': typeof RecebimentoRcSyncRoute
  '/manobra/': typeof ManobraIndexRoute
  '/passagem-bastao/': typeof PassagemBastaoIndexRoute
  '/peso-variavel/': typeof PesoVariavelIndexRoute
  '/recebimento-rc/': typeof RecebimentoRcIndexRoute
  '/peso-variavel/$id/resumo': typeof PesoVariavelIdResumoRoute
  '/recebimento-rc/$id/avarias': typeof RecebimentoRcIdAvariasRoute
  '/recebimento-rc/$id/checklist': typeof RecebimentoRcIdChecklistRoute
  '/recebimento-rc/$id/itens': typeof RecebimentoRcIdItensRoute
  '/recebimento-rc/$id/resumo': typeof RecebimentoRcIdResumoRoute
  '/peso-variavel/$id/': typeof PesoVariavelIdIndexRoute
  '/recebimento-rc/$id/': typeof RecebimentoRcIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alterar-senha': typeof AlterarSenhaRoute
  '/login': typeof LoginRoute
  '/passagem-bastao/resumo': typeof PassagemBastaoResumoRoute
  '/rastreio/$token': typeof RastreioTokenRoute
  '/recebimento-rc/sync': typeof RecebimentoRcSyncRoute
  '/manobra': typeof ManobraIndexRoute
  '/passagem-bastao': typeof PassagemBastaoIndexRoute
  '/peso-variavel': typeof PesoVariavelIndexRoute
  '/recebimento-rc': typeof RecebimentoRcIndexRoute
  '/peso-variavel/$id/resumo': typeof PesoVariavelIdResumoRoute
  '/recebimento-rc/$id/avarias': typeof RecebimentoRcIdAvariasRoute
  '/recebimento-rc/$id/checklist': typeof RecebimentoRcIdChecklistRoute
  '/recebimento-rc/$id/itens': typeof RecebimentoRcIdItensRoute
  '/recebimento-rc/$id/resumo': typeof RecebimentoRcIdResumoRoute
  '/peso-variavel/$id': typeof PesoVariavelIdIndexRoute
  '/recebimento-rc/$id': typeof RecebimentoRcIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/recebimento-rc': typeof RecebimentoRcRouteRouteWithChildren
  '/alterar-senha': typeof AlterarSenhaRoute
  '/login': typeof LoginRoute
  '/passagem-bastao/resumo': typeof PassagemBastaoResumoRoute
  '/peso-variavel/$id': typeof PesoVariavelIdRouteWithChildren
  '/rastreio/$token': typeof RastreioTokenRoute
  '/recebimento-rc/$id': typeof RecebimentoRcIdRouteWithChildren
  '/recebimento-rc/sync': typeof RecebimentoRcSyncRoute
  '/manobra/': typeof ManobraIndexRoute
  '/passagem-bastao/': typeof PassagemBastaoIndexRoute
  '/peso-variavel/': typeof PesoVariavelIndexRoute
  '/recebimento-rc/': typeof RecebimentoRcIndexRoute
  '/peso-variavel/$id/resumo': typeof PesoVariavelIdResumoRoute
  '/recebimento-rc/$id/avarias': typeof RecebimentoRcIdAvariasRoute
  '/recebimento-rc/$id/checklist': typeof RecebimentoRcIdChecklistRoute
  '/recebimento-rc/$id/itens': typeof RecebimentoRcIdItensRoute
  '/recebimento-rc/$id/resumo': typeof RecebimentoRcIdResumoRoute
  '/peso-variavel/$id/': typeof PesoVariavelIdIndexRoute
  '/recebimento-rc/$id/': typeof RecebimentoRcIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/recebimento-rc'
    | '/alterar-senha'
    | '/login'
    | '/passagem-bastao/resumo'
    | '/peso-variavel/$id'
    | '/rastreio/$token'
    | '/recebimento-rc/$id'
    | '/recebimento-rc/sync'
    | '/manobra/'
    | '/passagem-bastao/'
    | '/peso-variavel/'
    | '/recebimento-rc/'
    | '/peso-variavel/$id/resumo'
    | '/recebimento-rc/$id/avarias'
    | '/recebimento-rc/$id/checklist'
    | '/recebimento-rc/$id/itens'
    | '/recebimento-rc/$id/resumo'
    | '/peso-variavel/$id/'
    | '/recebimento-rc/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alterar-senha'
    | '/login'
    | '/passagem-bastao/resumo'
    | '/rastreio/$token'
    | '/recebimento-rc/sync'
    | '/manobra'
    | '/passagem-bastao'
    | '/peso-variavel'
    | '/recebimento-rc'
    | '/peso-variavel/$id/resumo'
    | '/recebimento-rc/$id/avarias'
    | '/recebimento-rc/$id/checklist'
    | '/recebimento-rc/$id/itens'
    | '/recebimento-rc/$id/resumo'
    | '/peso-variavel/$id'
    | '/recebimento-rc/$id'
  id:
    | '__root__'
    | '/'
    | '/recebimento-rc'
    | '/alterar-senha'
    | '/login'
    | '/passagem-bastao/resumo'
    | '/peso-variavel/$id'
    | '/rastreio/$token'
    | '/recebimento-rc/$id'
    | '/recebimento-rc/sync'
    | '/manobra/'
    | '/passagem-bastao/'
    | '/peso-variavel/'
    | '/recebimento-rc/'
    | '/peso-variavel/$id/resumo'
    | '/recebimento-rc/$id/avarias'
    | '/recebimento-rc/$id/checklist'
    | '/recebimento-rc/$id/itens'
    | '/recebimento-rc/$id/resumo'
    | '/peso-variavel/$id/'
    | '/recebimento-rc/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RecebimentoRcRouteRoute: typeof RecebimentoRcRouteRouteWithChildren
  AlterarSenhaRoute: typeof AlterarSenhaRoute
  LoginRoute: typeof LoginRoute
  PassagemBastaoResumoRoute: typeof PassagemBastaoResumoRoute
  PesoVariavelIdRoute: typeof PesoVariavelIdRouteWithChildren
  RastreioTokenRoute: typeof RastreioTokenRoute
  ManobraIndexRoute: typeof ManobraIndexRoute
  PassagemBastaoIndexRoute: typeof PassagemBastaoIndexRoute
  PesoVariavelIndexRoute: typeof PesoVariavelIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alterar-senha': {
      id: '/alterar-senha'
      path: '/alterar-senha'
      fullPath: '/alterar-senha'
      preLoaderRoute: typeof AlterarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recebimento-rc': {
      id: '/recebimento-rc'
      path: '/recebimento-rc'
      fullPath: '/recebimento-rc'
      preLoaderRoute: typeof RecebimentoRcRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recebimento-rc/': {
      id: '/recebimento-rc/'
      path: '/'
      fullPath: '/recebimento-rc/'
      preLoaderRoute: typeof RecebimentoRcIndexRouteImport
      parentRoute: typeof RecebimentoRcRouteRoute
    }
    '/peso-variavel/': {
      id: '/peso-variavel/'
      path: '/peso-variavel'
      fullPath: '/peso-variavel/'
      preLoaderRoute: typeof PesoVariavelIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passagem-bastao/': {
      id: '/passagem-bastao/'
      path: '/passagem-bastao'
      fullPath: '/passagem-bastao/'
      preLoaderRoute: typeof PassagemBastaoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manobra/': {
      id: '/manobra/'
      path: '/manobra'
      fullPath: '/manobra/'
      preLoaderRoute: typeof ManobraIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recebimento-rc/sync': {
      id: '/recebimento-rc/sync'
      path: '/sync'
      fullPath: '/recebimento-rc/sync'
      preLoaderRoute: typeof RecebimentoRcSyncRouteImport
      parentRoute: typeof RecebimentoRcRouteRoute
    }
    '/recebimento-rc/$id': {
      id: '/recebimento-rc/$id'
      path: '/$id'
      fullPath: '/recebimento-rc/$id'
      preLoaderRoute: typeof RecebimentoRcIdRouteImport
      parentRoute: typeof RecebimentoRcRouteRoute
    }
    '/rastreio/$token': {
      id: '/rastreio/$token'
      path: '/rastreio/$token'
      fullPath: '/rastreio/$token'
      preLoaderRoute: typeof RastreioTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/peso-variavel/$id': {
      id: '/peso-variavel/$id'
      path: '/peso-variavel/$id'
      fullPath: '/peso-variavel/$id'
      preLoaderRoute: typeof PesoVariavelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passagem-bastao/resumo': {
      id: '/passagem-bastao/resumo'
      path: '/passagem-bastao/resumo'
      fullPath: '/passagem-bastao/resumo'
      preLoaderRoute: typeof PassagemBastaoResumoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recebimento-rc/$id/': {
      id: '/recebimento-rc/$id/'
      path: '/'
      fullPath: '/recebimento-rc/$id/'
      preLoaderRoute: typeof RecebimentoRcIdIndexRouteImport
      parentRoute: typeof RecebimentoRcIdRoute
    }
    '/peso-variavel/$id/': {
      id: '/peso-variavel/$id/'
      path: '/'
      fullPath: '/peso-variavel/$id/'
      preLoaderRoute: typeof PesoVariavelIdIndexRouteImport
      parentRoute: typeof PesoVariavelIdRoute
    }
    '/recebimento-rc/$id/resumo': {
      id: '/recebimento-rc/$id/resumo'
      path: '/resumo'
      fullPath: '/recebimento-rc/$id/resumo'
      preLoaderRoute: typeof RecebimentoRcIdResumoRouteImport
      parentRoute: typeof RecebimentoRcIdRoute
    }
    '/recebimento-rc/$id/itens': {
      id: '/recebimento-rc/$id/itens'
      path: '/itens'
      fullPath: '/recebimento-rc/$id/itens'
      preLoaderRoute: typeof RecebimentoRcIdItensRouteImport
      parentRoute: typeof RecebimentoRcIdRoute
    }
    '/recebimento-rc/$id/checklist': {
      id: '/recebimento-rc/$id/checklist'
      path: '/checklist'
      fullPath: '/recebimento-rc/$id/checklist'
      preLoaderRoute: typeof RecebimentoRcIdChecklistRouteImport
      parentRoute: typeof RecebimentoRcIdRoute
    }
    '/recebimento-rc/$id/avarias': {
      id: '/recebimento-rc/$id/avarias'
      path: '/avarias'
      fullPath: '/recebimento-rc/$id/avarias'
      preLoaderRoute: typeof RecebimentoRcIdAvariasRouteImport
      parentRoute: typeof RecebimentoRcIdRoute
    }
    '/peso-variavel/$id/resumo': {
      id: '/peso-variavel/$id/resumo'
      path: '/resumo'
      fullPath: '/peso-variavel/$id/resumo'
      preLoaderRoute: typeof PesoVariavelIdResumoRouteImport
      parentRoute: typeof PesoVariavelIdRoute
    }
  }
}

interface RecebimentoRcIdRouteChildren {
  RecebimentoRcIdAvariasRoute: typeof RecebimentoRcIdAvariasRoute
  RecebimentoRcIdChecklistRoute: typeof RecebimentoRcIdChecklistRoute
  RecebimentoRcIdItensRoute: typeof RecebimentoRcIdItensRoute
  RecebimentoRcIdResumoRoute: typeof RecebimentoRcIdResumoRoute
  RecebimentoRcIdIndexRoute: typeof RecebimentoRcIdIndexRoute
}

const RecebimentoRcIdRouteChildren: RecebimentoRcIdRouteChildren = {
  RecebimentoRcIdAvariasRoute: RecebimentoRcIdAvariasRoute,
  RecebimentoRcIdChecklistRoute: RecebimentoRcIdChecklistRoute,
  RecebimentoRcIdItensRoute: RecebimentoRcIdItensRoute,
  RecebimentoRcIdResumoRoute: RecebimentoRcIdResumoRoute,
  RecebimentoRcIdIndexRoute: RecebimentoRcIdIndexRoute,
}

const RecebimentoRcIdRouteWithChildren = RecebimentoRcIdRoute._addFileChildren(
  RecebimentoRcIdRouteChildren,
)

interface RecebimentoRcRouteRouteChildren {
  RecebimentoRcIdRoute: typeof RecebimentoRcIdRouteWithChildren
  RecebimentoRcSyncRoute: typeof RecebimentoRcSyncRoute
  RecebimentoRcIndexRoute: typeof RecebimentoRcIndexRoute
}

const RecebimentoRcRouteRouteChildren: RecebimentoRcRouteRouteChildren = {
  RecebimentoRcIdRoute: RecebimentoRcIdRouteWithChildren,
  RecebimentoRcSyncRoute: RecebimentoRcSyncRoute,
  RecebimentoRcIndexRoute: RecebimentoRcIndexRoute,
}

const RecebimentoRcRouteRouteWithChildren =
  RecebimentoRcRouteRoute._addFileChildren(RecebimentoRcRouteRouteChildren)

interface PesoVariavelIdRouteChildren {
  PesoVariavelIdResumoRoute: typeof PesoVariavelIdResumoRoute
  PesoVariavelIdIndexRoute: typeof PesoVariavelIdIndexRoute
}

const PesoVariavelIdRouteChildren: PesoVariavelIdRouteChildren = {
  PesoVariavelIdResumoRoute: PesoVariavelIdResumoRoute,
  PesoVariavelIdIndexRoute: PesoVariavelIdIndexRoute,
}

const PesoVariavelIdRouteWithChildren = PesoVariavelIdRoute._addFileChildren(
  PesoVariavelIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RecebimentoRcRouteRoute: RecebimentoRcRouteRouteWithChildren,
  AlterarSenhaRoute: AlterarSenhaRoute,
  LoginRoute: LoginRoute,
  PassagemBastaoResumoRoute: PassagemBastaoResumoRoute,
  PesoVariavelIdRoute: PesoVariavelIdRouteWithChildren,
  RastreioTokenRoute: RastreioTokenRoute,
  ManobraIndexRoute: ManobraIndexRoute,
  PassagemBastaoIndexRoute: PassagemBastaoIndexRoute,
  PesoVariavelIndexRoute: PesoVariavelIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
