/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AlterarSenhaRouteImport } from './routes/alterar-senha'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RecebimentoIndexRouteImport } from './routes/recebimento/index'
import { Route as RecebimentoV2IndexRouteImport } from './routes/recebimento-v2/index'
import { Route as PesoVariavelIndexRouteImport } from './routes/peso-variavel/index'
import { Route as PassagemBastaoIndexRouteImport } from './routes/passagem-bastao/index'
import { Route as ManobraIndexRouteImport } from './routes/manobra/index'
import { Route as RecebimentoIdRouteImport } from './routes/recebimento/$id'
import { Route as RecebimentoV2IdRouteImport } from './routes/recebimento-v2/$id'
import { Route as RastreioTokenRouteImport } from './routes/rastreio/$token'
import { Route as PesoVariavelIdRouteImport } from './routes/peso-variavel/$id'
import { Route as PassagemBastaoResumoRouteImport } from './routes/passagem-bastao/resumo'
import { Route as RecebimentoIdIndexRouteImport } from './routes/recebimento/$id.index'
import { Route as RecebimentoV2IdIndexRouteImport } from './routes/recebimento-v2/$id.index'
import { Route as PesoVariavelIdIndexRouteImport } from './routes/peso-variavel/$id.index'
import { Route as RecebimentoIdTerminoRouteImport } from './routes/recebimento/$id.termino'
import { Route as RecebimentoIdItensRouteImport } from './routes/recebimento/$id.itens'
import { Route as RecebimentoIdChecklistRouteImport } from './routes/recebimento/$id.checklist'
import { Route as RecebimentoIdAvariaRouteImport } from './routes/recebimento/$id.avaria'
import { Route as RecebimentoV2IdSyncRouteImport } from './routes/recebimento-v2/$id.sync'
import { Route as RecebimentoV2IdResumoRouteImport } from './routes/recebimento-v2/$id.resumo'
import { Route as RecebimentoV2IdPreparacaoRouteImport } from './routes/recebimento-v2/$id.preparacao'
import { Route as RecebimentoV2IdItensRouteImport } from './routes/recebimento-v2/$id.itens'
import { Route as RecebimentoV2IdConflitoRouteImport } from './routes/recebimento-v2/$id.conflito'
import { Route as RecebimentoV2IdChecklistRouteImport } from './routes/recebimento-v2/$id.checklist'
import { Route as RecebimentoV2IdAvariasRouteImport } from './routes/recebimento-v2/$id.avarias'
import { Route as PesoVariavelIdResumoRouteImport } from './routes/peso-variavel/$id.resumo'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AlterarSenhaRoute = AlterarSenhaRouteImport.update({
  id: '/alterar-senha',
  path: '/alterar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecebimentoIndexRoute = RecebimentoIndexRouteImport.update({
  id: '/recebimento/',
  path: '/recebimento/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecebimentoV2IndexRoute = RecebimentoV2IndexRouteImport.update({
  id: '/recebimento-v2/',
  path: '/recebimento-v2/',
  getParentRoute: () => rootRouteImport,
} as any)
const PesoVariavelIndexRoute = PesoVariavelIndexRouteImport.update({
  id: '/peso-variavel/',
  path: '/peso-variavel/',
  getParentRoute: () => rootRouteImport,
} as any)
const PassagemBastaoIndexRoute = PassagemBastaoIndexRouteImport.update({
  id: '/passagem-bastao/',
  path: '/passagem-bastao/',
  getParentRoute: () => rootRouteImport,
} as any)
const ManobraIndexRoute = ManobraIndexRouteImport.update({
  id: '/manobra/',
  path: '/manobra/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecebimentoIdRoute = RecebimentoIdRouteImport.update({
  id: '/recebimento/$id',
  path: '/recebimento/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RecebimentoV2IdRoute = RecebimentoV2IdRouteImport.update({
  id: '/recebimento-v2/$id',
  path: '/recebimento-v2/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RastreioTokenRoute = RastreioTokenRouteImport.update({
  id: '/rastreio/$token',
  path: '/rastreio/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const PesoVariavelIdRoute = PesoVariavelIdRouteImport.update({
  id: '/peso-variavel/$id',
  path: '/peso-variavel/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PassagemBastaoResumoRoute = PassagemBastaoResumoRouteImport.update({
  id: '/passagem-bastao/resumo',
  path: '/passagem-bastao/resumo',
  getParentRoute: () => rootRouteImport,
} as any)
const RecebimentoIdIndexRoute = RecebimentoIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RecebimentoIdRoute,
} as any)
const RecebimentoV2IdIndexRoute = RecebimentoV2IdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RecebimentoV2IdRoute,
} as any)
const PesoVariavelIdIndexRoute = PesoVariavelIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PesoVariavelIdRoute,
} as any)
const RecebimentoIdTerminoRoute = RecebimentoIdTerminoRouteImport.update({
  id: '/termino',
  path: '/termino',
  getParentRoute: () => RecebimentoIdRoute,
} as any)
const RecebimentoIdItensRoute = RecebimentoIdItensRouteImport.update({
  id: '/itens',
  path: '/itens',
  getParentRoute: () => RecebimentoIdRoute,
} as any)
const RecebimentoIdChecklistRoute = RecebimentoIdChecklistRouteImport.update({
  id: '/checklist',
  path: '/checklist',
  getParentRoute: () => RecebimentoIdRoute,
} as any)
const RecebimentoIdAvariaRoute = RecebimentoIdAvariaRouteImport.update({
  id: '/avaria',
  path: '/avaria',
  getParentRoute: () => RecebimentoIdRoute,
} as any)
const RecebimentoV2IdSyncRoute = RecebimentoV2IdSyncRouteImport.update({
  id: '/sync',
  path: '/sync',
  getParentRoute: () => RecebimentoV2IdRoute,
} as any)
const RecebimentoV2IdResumoRoute = RecebimentoV2IdResumoRouteImport.update({
  id: '/resumo',
  path: '/resumo',
  getParentRoute: () => RecebimentoV2IdRoute,
} as any)
const RecebimentoV2IdPreparacaoRoute =
  RecebimentoV2IdPreparacaoRouteImport.update({
    id: '/preparacao',
    path: '/preparacao',
    getParentRoute: () => RecebimentoV2IdRoute,
  } as any)
const RecebimentoV2IdItensRoute = RecebimentoV2IdItensRouteImport.update({
  id: '/itens',
  path: '/itens',
  getParentRoute: () => RecebimentoV2IdRoute,
} as any)
const RecebimentoV2IdConflitoRoute = RecebimentoV2IdConflitoRouteImport.update({
  id: '/conflito',
  path: '/conflito',
  getParentRoute: () => RecebimentoV2IdRoute,
} as any)
const RecebimentoV2IdChecklistRoute =
  RecebimentoV2IdChecklistRouteImport.update({
    id: '/checklist',
    path: '/checklist',
    getParentRoute: () => RecebimentoV2IdRoute,
  } as any)
const RecebimentoV2IdAvariasRoute = RecebimentoV2IdAvariasRouteImport.update({
  id: '/avarias',
  path: '/avarias',
  getParentRoute: () => RecebimentoV2IdRoute,
} as any)
const PesoVariavelIdResumoRoute = PesoVariavelIdResumoRouteImport.update({
  id: '/resumo',
  path: '/resumo',
  getParentRoute: () => PesoVariavelIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alterar-senha': typeof AlterarSenhaRoute
  '/login': typeof LoginRoute
  '/passagem-bastao/resumo': typeof PassagemBastaoResumoRoute
  '/peso-variavel/$id': typeof PesoVariavelIdRouteWithChildren
  '/rastreio/$token': typeof RastreioTokenRoute
  '/recebimento-v2/$id': typeof RecebimentoV2IdRouteWithChildren
  '/recebimento/$id': typeof RecebimentoIdRouteWithChildren
  '/manobra/': typeof ManobraIndexRoute
  '/passagem-bastao/': typeof PassagemBastaoIndexRoute
  '/peso-variavel/': typeof PesoVariavelIndexRoute
  '/recebimento-v2/': typeof RecebimentoV2IndexRoute
  '/recebimento/': typeof RecebimentoIndexRoute
  '/peso-variavel/$id/resumo': typeof PesoVariavelIdResumoRoute
  '/recebimento-v2/$id/avarias': typeof RecebimentoV2IdAvariasRoute
  '/recebimento-v2/$id/checklist': typeof RecebimentoV2IdChecklistRoute
  '/recebimento-v2/$id/conflito': typeof RecebimentoV2IdConflitoRoute
  '/recebimento-v2/$id/itens': typeof RecebimentoV2IdItensRoute
  '/recebimento-v2/$id/preparacao': typeof RecebimentoV2IdPreparacaoRoute
  '/recebimento-v2/$id/resumo': typeof RecebimentoV2IdResumoRoute
  '/recebimento-v2/$id/sync': typeof RecebimentoV2IdSyncRoute
  '/recebimento/$id/avaria': typeof RecebimentoIdAvariaRoute
  '/recebimento/$id/checklist': typeof RecebimentoIdChecklistRoute
  '/recebimento/$id/itens': typeof RecebimentoIdItensRoute
  '/recebimento/$id/termino': typeof RecebimentoIdTerminoRoute
  '/peso-variavel/$id/': typeof PesoVariavelIdIndexRoute
  '/recebimento-v2/$id/': typeof RecebimentoV2IdIndexRoute
  '/recebimento/$id/': typeof RecebimentoIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alterar-senha': typeof AlterarSenhaRoute
  '/login': typeof LoginRoute
  '/passagem-bastao/resumo': typeof PassagemBastaoResumoRoute
  '/rastreio/$token': typeof RastreioTokenRoute
  '/manobra': typeof ManobraIndexRoute
  '/passagem-bastao': typeof PassagemBastaoIndexRoute
  '/peso-variavel': typeof PesoVariavelIndexRoute
  '/recebimento-v2': typeof RecebimentoV2IndexRoute
  '/recebimento': typeof RecebimentoIndexRoute
  '/peso-variavel/$id/resumo': typeof PesoVariavelIdResumoRoute
  '/recebimento-v2/$id/avarias': typeof RecebimentoV2IdAvariasRoute
  '/recebimento-v2/$id/checklist': typeof RecebimentoV2IdChecklistRoute
  '/recebimento-v2/$id/conflito': typeof RecebimentoV2IdConflitoRoute
  '/recebimento-v2/$id/itens': typeof RecebimentoV2IdItensRoute
  '/recebimento-v2/$id/preparacao': typeof RecebimentoV2IdPreparacaoRoute
  '/recebimento-v2/$id/resumo': typeof RecebimentoV2IdResumoRoute
  '/recebimento-v2/$id/sync': typeof RecebimentoV2IdSyncRoute
  '/recebimento/$id/avaria': typeof RecebimentoIdAvariaRoute
  '/recebimento/$id/checklist': typeof RecebimentoIdChecklistRoute
  '/recebimento/$id/itens': typeof RecebimentoIdItensRoute
  '/recebimento/$id/termino': typeof RecebimentoIdTerminoRoute
  '/peso-variavel/$id': typeof PesoVariavelIdIndexRoute
  '/recebimento-v2/$id': typeof RecebimentoV2IdIndexRoute
  '/recebimento/$id': typeof RecebimentoIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alterar-senha': typeof AlterarSenhaRoute
  '/login': typeof LoginRoute
  '/passagem-bastao/resumo': typeof PassagemBastaoResumoRoute
  '/peso-variavel/$id': typeof PesoVariavelIdRouteWithChildren
  '/rastreio/$token': typeof RastreioTokenRoute
  '/recebimento-v2/$id': typeof RecebimentoV2IdRouteWithChildren
  '/recebimento/$id': typeof RecebimentoIdRouteWithChildren
  '/manobra/': typeof ManobraIndexRoute
  '/passagem-bastao/': typeof PassagemBastaoIndexRoute
  '/peso-variavel/': typeof PesoVariavelIndexRoute
  '/recebimento-v2/': typeof RecebimentoV2IndexRoute
  '/recebimento/': typeof RecebimentoIndexRoute
  '/peso-variavel/$id/resumo': typeof PesoVariavelIdResumoRoute
  '/recebimento-v2/$id/avarias': typeof RecebimentoV2IdAvariasRoute
  '/recebimento-v2/$id/checklist': typeof RecebimentoV2IdChecklistRoute
  '/recebimento-v2/$id/conflito': typeof RecebimentoV2IdConflitoRoute
  '/recebimento-v2/$id/itens': typeof RecebimentoV2IdItensRoute
  '/recebimento-v2/$id/preparacao': typeof RecebimentoV2IdPreparacaoRoute
  '/recebimento-v2/$id/resumo': typeof RecebimentoV2IdResumoRoute
  '/recebimento-v2/$id/sync': typeof RecebimentoV2IdSyncRoute
  '/recebimento/$id/avaria': typeof RecebimentoIdAvariaRoute
  '/recebimento/$id/checklist': typeof RecebimentoIdChecklistRoute
  '/recebimento/$id/itens': typeof RecebimentoIdItensRoute
  '/recebimento/$id/termino': typeof RecebimentoIdTerminoRoute
  '/peso-variavel/$id/': typeof PesoVariavelIdIndexRoute
  '/recebimento-v2/$id/': typeof RecebimentoV2IdIndexRoute
  '/recebimento/$id/': typeof RecebimentoIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alterar-senha'
    | '/login'
    | '/passagem-bastao/resumo'
    | '/peso-variavel/$id'
    | '/rastreio/$token'
    | '/recebimento-v2/$id'
    | '/recebimento/$id'
    | '/manobra/'
    | '/passagem-bastao/'
    | '/peso-variavel/'
    | '/recebimento-v2/'
    | '/recebimento/'
    | '/peso-variavel/$id/resumo'
    | '/recebimento-v2/$id/avarias'
    | '/recebimento-v2/$id/checklist'
    | '/recebimento-v2/$id/conflito'
    | '/recebimento-v2/$id/itens'
    | '/recebimento-v2/$id/preparacao'
    | '/recebimento-v2/$id/resumo'
    | '/recebimento-v2/$id/sync'
    | '/recebimento/$id/avaria'
    | '/recebimento/$id/checklist'
    | '/recebimento/$id/itens'
    | '/recebimento/$id/termino'
    | '/peso-variavel/$id/'
    | '/recebimento-v2/$id/'
    | '/recebimento/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alterar-senha'
    | '/login'
    | '/passagem-bastao/resumo'
    | '/rastreio/$token'
    | '/manobra'
    | '/passagem-bastao'
    | '/peso-variavel'
    | '/recebimento-v2'
    | '/recebimento'
    | '/peso-variavel/$id/resumo'
    | '/recebimento-v2/$id/avarias'
    | '/recebimento-v2/$id/checklist'
    | '/recebimento-v2/$id/conflito'
    | '/recebimento-v2/$id/itens'
    | '/recebimento-v2/$id/preparacao'
    | '/recebimento-v2/$id/resumo'
    | '/recebimento-v2/$id/sync'
    | '/recebimento/$id/avaria'
    | '/recebimento/$id/checklist'
    | '/recebimento/$id/itens'
    | '/recebimento/$id/termino'
    | '/peso-variavel/$id'
    | '/recebimento-v2/$id'
    | '/recebimento/$id'
  id:
    | '__root__'
    | '/'
    | '/alterar-senha'
    | '/login'
    | '/passagem-bastao/resumo'
    | '/peso-variavel/$id'
    | '/rastreio/$token'
    | '/recebimento-v2/$id'
    | '/recebimento/$id'
    | '/manobra/'
    | '/passagem-bastao/'
    | '/peso-variavel/'
    | '/recebimento-v2/'
    | '/recebimento/'
    | '/peso-variavel/$id/resumo'
    | '/recebimento-v2/$id/avarias'
    | '/recebimento-v2/$id/checklist'
    | '/recebimento-v2/$id/conflito'
    | '/recebimento-v2/$id/itens'
    | '/recebimento-v2/$id/preparacao'
    | '/recebimento-v2/$id/resumo'
    | '/recebimento-v2/$id/sync'
    | '/recebimento/$id/avaria'
    | '/recebimento/$id/checklist'
    | '/recebimento/$id/itens'
    | '/recebimento/$id/termino'
    | '/peso-variavel/$id/'
    | '/recebimento-v2/$id/'
    | '/recebimento/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlterarSenhaRoute: typeof AlterarSenhaRoute
  LoginRoute: typeof LoginRoute
  PassagemBastaoResumoRoute: typeof PassagemBastaoResumoRoute
  PesoVariavelIdRoute: typeof PesoVariavelIdRouteWithChildren
  RastreioTokenRoute: typeof RastreioTokenRoute
  RecebimentoV2IdRoute: typeof RecebimentoV2IdRouteWithChildren
  RecebimentoIdRoute: typeof RecebimentoIdRouteWithChildren
  ManobraIndexRoute: typeof ManobraIndexRoute
  PassagemBastaoIndexRoute: typeof PassagemBastaoIndexRoute
  PesoVariavelIndexRoute: typeof PesoVariavelIndexRoute
  RecebimentoV2IndexRoute: typeof RecebimentoV2IndexRoute
  RecebimentoIndexRoute: typeof RecebimentoIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alterar-senha': {
      id: '/alterar-senha'
      path: '/alterar-senha'
      fullPath: '/alterar-senha'
      preLoaderRoute: typeof AlterarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recebimento/': {
      id: '/recebimento/'
      path: '/recebimento'
      fullPath: '/recebimento/'
      preLoaderRoute: typeof RecebimentoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recebimento-v2/': {
      id: '/recebimento-v2/'
      path: '/recebimento-v2'
      fullPath: '/recebimento-v2/'
      preLoaderRoute: typeof RecebimentoV2IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/peso-variavel/': {
      id: '/peso-variavel/'
      path: '/peso-variavel'
      fullPath: '/peso-variavel/'
      preLoaderRoute: typeof PesoVariavelIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passagem-bastao/': {
      id: '/passagem-bastao/'
      path: '/passagem-bastao'
      fullPath: '/passagem-bastao/'
      preLoaderRoute: typeof PassagemBastaoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manobra/': {
      id: '/manobra/'
      path: '/manobra'
      fullPath: '/manobra/'
      preLoaderRoute: typeof ManobraIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recebimento/$id': {
      id: '/recebimento/$id'
      path: '/recebimento/$id'
      fullPath: '/recebimento/$id'
      preLoaderRoute: typeof RecebimentoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recebimento-v2/$id': {
      id: '/recebimento-v2/$id'
      path: '/recebimento-v2/$id'
      fullPath: '/recebimento-v2/$id'
      preLoaderRoute: typeof RecebimentoV2IdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rastreio/$token': {
      id: '/rastreio/$token'
      path: '/rastreio/$token'
      fullPath: '/rastreio/$token'
      preLoaderRoute: typeof RastreioTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/peso-variavel/$id': {
      id: '/peso-variavel/$id'
      path: '/peso-variavel/$id'
      fullPath: '/peso-variavel/$id'
      preLoaderRoute: typeof PesoVariavelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passagem-bastao/resumo': {
      id: '/passagem-bastao/resumo'
      path: '/passagem-bastao/resumo'
      fullPath: '/passagem-bastao/resumo'
      preLoaderRoute: typeof PassagemBastaoResumoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recebimento/$id/': {
      id: '/recebimento/$id/'
      path: '/'
      fullPath: '/recebimento/$id/'
      preLoaderRoute: typeof RecebimentoIdIndexRouteImport
      parentRoute: typeof RecebimentoIdRoute
    }
    '/recebimento-v2/$id/': {
      id: '/recebimento-v2/$id/'
      path: '/'
      fullPath: '/recebimento-v2/$id/'
      preLoaderRoute: typeof RecebimentoV2IdIndexRouteImport
      parentRoute: typeof RecebimentoV2IdRoute
    }
    '/peso-variavel/$id/': {
      id: '/peso-variavel/$id/'
      path: '/'
      fullPath: '/peso-variavel/$id/'
      preLoaderRoute: typeof PesoVariavelIdIndexRouteImport
      parentRoute: typeof PesoVariavelIdRoute
    }
    '/recebimento/$id/termino': {
      id: '/recebimento/$id/termino'
      path: '/termino'
      fullPath: '/recebimento/$id/termino'
      preLoaderRoute: typeof RecebimentoIdTerminoRouteImport
      parentRoute: typeof RecebimentoIdRoute
    }
    '/recebimento/$id/itens': {
      id: '/recebimento/$id/itens'
      path: '/itens'
      fullPath: '/recebimento/$id/itens'
      preLoaderRoute: typeof RecebimentoIdItensRouteImport
      parentRoute: typeof RecebimentoIdRoute
    }
    '/recebimento/$id/checklist': {
      id: '/recebimento/$id/checklist'
      path: '/checklist'
      fullPath: '/recebimento/$id/checklist'
      preLoaderRoute: typeof RecebimentoIdChecklistRouteImport
      parentRoute: typeof RecebimentoIdRoute
    }
    '/recebimento/$id/avaria': {
      id: '/recebimento/$id/avaria'
      path: '/avaria'
      fullPath: '/recebimento/$id/avaria'
      preLoaderRoute: typeof RecebimentoIdAvariaRouteImport
      parentRoute: typeof RecebimentoIdRoute
    }
    '/recebimento-v2/$id/sync': {
      id: '/recebimento-v2/$id/sync'
      path: '/sync'
      fullPath: '/recebimento-v2/$id/sync'
      preLoaderRoute: typeof RecebimentoV2IdSyncRouteImport
      parentRoute: typeof RecebimentoV2IdRoute
    }
    '/recebimento-v2/$id/resumo': {
      id: '/recebimento-v2/$id/resumo'
      path: '/resumo'
      fullPath: '/recebimento-v2/$id/resumo'
      preLoaderRoute: typeof RecebimentoV2IdResumoRouteImport
      parentRoute: typeof RecebimentoV2IdRoute
    }
    '/recebimento-v2/$id/preparacao': {
      id: '/recebimento-v2/$id/preparacao'
      path: '/preparacao'
      fullPath: '/recebimento-v2/$id/preparacao'
      preLoaderRoute: typeof RecebimentoV2IdPreparacaoRouteImport
      parentRoute: typeof RecebimentoV2IdRoute
    }
    '/recebimento-v2/$id/itens': {
      id: '/recebimento-v2/$id/itens'
      path: '/itens'
      fullPath: '/recebimento-v2/$id/itens'
      preLoaderRoute: typeof RecebimentoV2IdItensRouteImport
      parentRoute: typeof RecebimentoV2IdRoute
    }
    '/recebimento-v2/$id/conflito': {
      id: '/recebimento-v2/$id/conflito'
      path: '/conflito'
      fullPath: '/recebimento-v2/$id/conflito'
      preLoaderRoute: typeof RecebimentoV2IdConflitoRouteImport
      parentRoute: typeof RecebimentoV2IdRoute
    }
    '/recebimento-v2/$id/checklist': {
      id: '/recebimento-v2/$id/checklist'
      path: '/checklist'
      fullPath: '/recebimento-v2/$id/checklist'
      preLoaderRoute: typeof RecebimentoV2IdChecklistRouteImport
      parentRoute: typeof RecebimentoV2IdRoute
    }
    '/recebimento-v2/$id/avarias': {
      id: '/recebimento-v2/$id/avarias'
      path: '/avarias'
      fullPath: '/recebimento-v2/$id/avarias'
      preLoaderRoute: typeof RecebimentoV2IdAvariasRouteImport
      parentRoute: typeof RecebimentoV2IdRoute
    }
    '/peso-variavel/$id/resumo': {
      id: '/peso-variavel/$id/resumo'
      path: '/resumo'
      fullPath: '/peso-variavel/$id/resumo'
      preLoaderRoute: typeof PesoVariavelIdResumoRouteImport
      parentRoute: typeof PesoVariavelIdRoute
    }
  }
}

interface PesoVariavelIdRouteChildren {
  PesoVariavelIdResumoRoute: typeof PesoVariavelIdResumoRoute
  PesoVariavelIdIndexRoute: typeof PesoVariavelIdIndexRoute
}

const PesoVariavelIdRouteChildren: PesoVariavelIdRouteChildren = {
  PesoVariavelIdResumoRoute: PesoVariavelIdResumoRoute,
  PesoVariavelIdIndexRoute: PesoVariavelIdIndexRoute,
}

const PesoVariavelIdRouteWithChildren = PesoVariavelIdRoute._addFileChildren(
  PesoVariavelIdRouteChildren,
)

interface RecebimentoV2IdRouteChildren {
  RecebimentoV2IdAvariasRoute: typeof RecebimentoV2IdAvariasRoute
  RecebimentoV2IdChecklistRoute: typeof RecebimentoV2IdChecklistRoute
  RecebimentoV2IdConflitoRoute: typeof RecebimentoV2IdConflitoRoute
  RecebimentoV2IdItensRoute: typeof RecebimentoV2IdItensRoute
  RecebimentoV2IdPreparacaoRoute: typeof RecebimentoV2IdPreparacaoRoute
  RecebimentoV2IdResumoRoute: typeof RecebimentoV2IdResumoRoute
  RecebimentoV2IdSyncRoute: typeof RecebimentoV2IdSyncRoute
  RecebimentoV2IdIndexRoute: typeof RecebimentoV2IdIndexRoute
}

const RecebimentoV2IdRouteChildren: RecebimentoV2IdRouteChildren = {
  RecebimentoV2IdAvariasRoute: RecebimentoV2IdAvariasRoute,
  RecebimentoV2IdChecklistRoute: RecebimentoV2IdChecklistRoute,
  RecebimentoV2IdConflitoRoute: RecebimentoV2IdConflitoRoute,
  RecebimentoV2IdItensRoute: RecebimentoV2IdItensRoute,
  RecebimentoV2IdPreparacaoRoute: RecebimentoV2IdPreparacaoRoute,
  RecebimentoV2IdResumoRoute: RecebimentoV2IdResumoRoute,
  RecebimentoV2IdSyncRoute: RecebimentoV2IdSyncRoute,
  RecebimentoV2IdIndexRoute: RecebimentoV2IdIndexRoute,
}

const RecebimentoV2IdRouteWithChildren = RecebimentoV2IdRoute._addFileChildren(
  RecebimentoV2IdRouteChildren,
)

interface RecebimentoIdRouteChildren {
  RecebimentoIdAvariaRoute: typeof RecebimentoIdAvariaRoute
  RecebimentoIdChecklistRoute: typeof RecebimentoIdChecklistRoute
  RecebimentoIdItensRoute: typeof RecebimentoIdItensRoute
  RecebimentoIdTerminoRoute: typeof RecebimentoIdTerminoRoute
  RecebimentoIdIndexRoute: typeof RecebimentoIdIndexRoute
}

const RecebimentoIdRouteChildren: RecebimentoIdRouteChildren = {
  RecebimentoIdAvariaRoute: RecebimentoIdAvariaRoute,
  RecebimentoIdChecklistRoute: RecebimentoIdChecklistRoute,
  RecebimentoIdItensRoute: RecebimentoIdItensRoute,
  RecebimentoIdTerminoRoute: RecebimentoIdTerminoRoute,
  RecebimentoIdIndexRoute: RecebimentoIdIndexRoute,
}

const RecebimentoIdRouteWithChildren = RecebimentoIdRoute._addFileChildren(
  RecebimentoIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlterarSenhaRoute: AlterarSenhaRoute,
  LoginRoute: LoginRoute,
  PassagemBastaoResumoRoute: PassagemBastaoResumoRoute,
  PesoVariavelIdRoute: PesoVariavelIdRouteWithChildren,
  RastreioTokenRoute: RastreioTokenRoute,
  RecebimentoV2IdRoute: RecebimentoV2IdRouteWithChildren,
  RecebimentoIdRoute: RecebimentoIdRouteWithChildren,
  ManobraIndexRoute: ManobraIndexRoute,
  PassagemBastaoIndexRoute: PassagemBastaoIndexRoute,
  PesoVariavelIndexRoute: PesoVariavelIndexRoute,
  RecebimentoV2IndexRoute: RecebimentoV2IndexRoute,
  RecebimentoIndexRoute: RecebimentoIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
