/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AcessoNegadoRouteImport } from './routes/acesso-negado'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SessaoPresencaIndexRouteImport } from './routes/sessao-presenca/index'
import { Route as IndicadoresIndexRouteImport } from './routes/indicadores/index'
import { Route as SessaoPresencaNovaRouteImport } from './routes/sessao-presenca/nova'
import { Route as SessaoPresencaSessaoIdRouteImport } from './routes/sessao-presenca/$sessaoId'
import { Route as OpWmsGestaoRecursosIndexRouteImport } from './routes/op-wms/gestao-recursos/index'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AcessoNegadoRoute = AcessoNegadoRouteImport.update({
  id: '/acesso-negado',
  path: '/acesso-negado',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessaoPresencaIndexRoute = SessaoPresencaIndexRouteImport.update({
  id: '/sessao-presenca/',
  path: '/sessao-presenca/',
  getParentRoute: () => rootRouteImport,
} as any)
const IndicadoresIndexRoute = IndicadoresIndexRouteImport.update({
  id: '/indicadores/',
  path: '/indicadores/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessaoPresencaNovaRoute = SessaoPresencaNovaRouteImport.update({
  id: '/sessao-presenca/nova',
  path: '/sessao-presenca/nova',
  getParentRoute: () => rootRouteImport,
} as any)
const SessaoPresencaSessaoIdRoute = SessaoPresencaSessaoIdRouteImport.update({
  id: '/sessao-presenca/$sessaoId',
  path: '/sessao-presenca/$sessaoId',
  getParentRoute: () => rootRouteImport,
} as any)
const OpWmsGestaoRecursosIndexRoute =
  OpWmsGestaoRecursosIndexRouteImport.update({
    id: '/op-wms/gestao-recursos/',
    path: '/op-wms/gestao-recursos/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acesso-negado': typeof AcessoNegadoRoute
  '/login': typeof LoginRoute
  '/sessao-presenca/$sessaoId': typeof SessaoPresencaSessaoIdRoute
  '/sessao-presenca/nova': typeof SessaoPresencaNovaRoute
  '/indicadores/': typeof IndicadoresIndexRoute
  '/sessao-presenca/': typeof SessaoPresencaIndexRoute
  '/op-wms/gestao-recursos/': typeof OpWmsGestaoRecursosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acesso-negado': typeof AcessoNegadoRoute
  '/login': typeof LoginRoute
  '/sessao-presenca/$sessaoId': typeof SessaoPresencaSessaoIdRoute
  '/sessao-presenca/nova': typeof SessaoPresencaNovaRoute
  '/indicadores': typeof IndicadoresIndexRoute
  '/sessao-presenca': typeof SessaoPresencaIndexRoute
  '/op-wms/gestao-recursos': typeof OpWmsGestaoRecursosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/acesso-negado': typeof AcessoNegadoRoute
  '/login': typeof LoginRoute
  '/sessao-presenca/$sessaoId': typeof SessaoPresencaSessaoIdRoute
  '/sessao-presenca/nova': typeof SessaoPresencaNovaRoute
  '/indicadores/': typeof IndicadoresIndexRoute
  '/sessao-presenca/': typeof SessaoPresencaIndexRoute
  '/op-wms/gestao-recursos/': typeof OpWmsGestaoRecursosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acesso-negado'
    | '/login'
    | '/sessao-presenca/$sessaoId'
    | '/sessao-presenca/nova'
    | '/indicadores/'
    | '/sessao-presenca/'
    | '/op-wms/gestao-recursos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acesso-negado'
    | '/login'
    | '/sessao-presenca/$sessaoId'
    | '/sessao-presenca/nova'
    | '/indicadores'
    | '/sessao-presenca'
    | '/op-wms/gestao-recursos'
  id:
    | '__root__'
    | '/'
    | '/acesso-negado'
    | '/login'
    | '/sessao-presenca/$sessaoId'
    | '/sessao-presenca/nova'
    | '/indicadores/'
    | '/sessao-presenca/'
    | '/op-wms/gestao-recursos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcessoNegadoRoute: typeof AcessoNegadoRoute
  LoginRoute: typeof LoginRoute
  SessaoPresencaSessaoIdRoute: typeof SessaoPresencaSessaoIdRoute
  SessaoPresencaNovaRoute: typeof SessaoPresencaNovaRoute
  IndicadoresIndexRoute: typeof IndicadoresIndexRoute
  SessaoPresencaIndexRoute: typeof SessaoPresencaIndexRoute
  OpWmsGestaoRecursosIndexRoute: typeof OpWmsGestaoRecursosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acesso-negado': {
      id: '/acesso-negado'
      path: '/acesso-negado'
      fullPath: '/acesso-negado'
      preLoaderRoute: typeof AcessoNegadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessao-presenca/': {
      id: '/sessao-presenca/'
      path: '/sessao-presenca'
      fullPath: '/sessao-presenca/'
      preLoaderRoute: typeof SessaoPresencaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/indicadores/': {
      id: '/indicadores/'
      path: '/indicadores'
      fullPath: '/indicadores/'
      preLoaderRoute: typeof IndicadoresIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessao-presenca/nova': {
      id: '/sessao-presenca/nova'
      path: '/sessao-presenca/nova'
      fullPath: '/sessao-presenca/nova'
      preLoaderRoute: typeof SessaoPresencaNovaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessao-presenca/$sessaoId': {
      id: '/sessao-presenca/$sessaoId'
      path: '/sessao-presenca/$sessaoId'
      fullPath: '/sessao-presenca/$sessaoId'
      preLoaderRoute: typeof SessaoPresencaSessaoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/op-wms/gestao-recursos/': {
      id: '/op-wms/gestao-recursos/'
      path: '/op-wms/gestao-recursos'
      fullPath: '/op-wms/gestao-recursos/'
      preLoaderRoute: typeof OpWmsGestaoRecursosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcessoNegadoRoute: AcessoNegadoRoute,
  LoginRoute: LoginRoute,
  SessaoPresencaSessaoIdRoute: SessaoPresencaSessaoIdRoute,
  SessaoPresencaNovaRoute: SessaoPresencaNovaRoute,
  IndicadoresIndexRoute: IndicadoresIndexRoute,
  SessaoPresencaIndexRoute: SessaoPresencaIndexRoute,
  OpWmsGestaoRecursosIndexRoute: OpWmsGestaoRecursosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
