/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SessaoPresencaIndexRouteImport } from './routes/sessao-presenca/index'
import { Route as RecebimentoIndexRouteImport } from './routes/recebimento/index'
import { Route as SessaoPresencaNovaRouteImport } from './routes/sessao-presenca/nova'
import { Route as SessaoPresencaSessaoIdRouteImport } from './routes/sessao-presenca/$sessaoId'
import { Route as RecebimentoGestaoRecursosIndexRouteImport } from './routes/recebimento/gestao-recursos/index'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessaoPresencaIndexRoute = SessaoPresencaIndexRouteImport.update({
  id: '/sessao-presenca/',
  path: '/sessao-presenca/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecebimentoIndexRoute = RecebimentoIndexRouteImport.update({
  id: '/recebimento/',
  path: '/recebimento/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessaoPresencaNovaRoute = SessaoPresencaNovaRouteImport.update({
  id: '/sessao-presenca/nova',
  path: '/sessao-presenca/nova',
  getParentRoute: () => rootRouteImport,
} as any)
const SessaoPresencaSessaoIdRoute = SessaoPresencaSessaoIdRouteImport.update({
  id: '/sessao-presenca/$sessaoId',
  path: '/sessao-presenca/$sessaoId',
  getParentRoute: () => rootRouteImport,
} as any)
const RecebimentoGestaoRecursosIndexRoute =
  RecebimentoGestaoRecursosIndexRouteImport.update({
    id: '/recebimento/gestao-recursos/',
    path: '/recebimento/gestao-recursos/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/sessao-presenca/$sessaoId': typeof SessaoPresencaSessaoIdRoute
  '/sessao-presenca/nova': typeof SessaoPresencaNovaRoute
  '/recebimento/': typeof RecebimentoIndexRoute
  '/sessao-presenca/': typeof SessaoPresencaIndexRoute
  '/recebimento/gestao-recursos/': typeof RecebimentoGestaoRecursosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/sessao-presenca/$sessaoId': typeof SessaoPresencaSessaoIdRoute
  '/sessao-presenca/nova': typeof SessaoPresencaNovaRoute
  '/recebimento': typeof RecebimentoIndexRoute
  '/sessao-presenca': typeof SessaoPresencaIndexRoute
  '/recebimento/gestao-recursos': typeof RecebimentoGestaoRecursosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/sessao-presenca/$sessaoId': typeof SessaoPresencaSessaoIdRoute
  '/sessao-presenca/nova': typeof SessaoPresencaNovaRoute
  '/recebimento/': typeof RecebimentoIndexRoute
  '/sessao-presenca/': typeof SessaoPresencaIndexRoute
  '/recebimento/gestao-recursos/': typeof RecebimentoGestaoRecursosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/sessao-presenca/$sessaoId'
    | '/sessao-presenca/nova'
    | '/recebimento/'
    | '/sessao-presenca/'
    | '/recebimento/gestao-recursos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/sessao-presenca/$sessaoId'
    | '/sessao-presenca/nova'
    | '/recebimento'
    | '/sessao-presenca'
    | '/recebimento/gestao-recursos'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/sessao-presenca/$sessaoId'
    | '/sessao-presenca/nova'
    | '/recebimento/'
    | '/sessao-presenca/'
    | '/recebimento/gestao-recursos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SessaoPresencaSessaoIdRoute: typeof SessaoPresencaSessaoIdRoute
  SessaoPresencaNovaRoute: typeof SessaoPresencaNovaRoute
  RecebimentoIndexRoute: typeof RecebimentoIndexRoute
  SessaoPresencaIndexRoute: typeof SessaoPresencaIndexRoute
  RecebimentoGestaoRecursosIndexRoute: typeof RecebimentoGestaoRecursosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessao-presenca/': {
      id: '/sessao-presenca/'
      path: '/sessao-presenca'
      fullPath: '/sessao-presenca/'
      preLoaderRoute: typeof SessaoPresencaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recebimento/': {
      id: '/recebimento/'
      path: '/recebimento'
      fullPath: '/recebimento/'
      preLoaderRoute: typeof RecebimentoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessao-presenca/nova': {
      id: '/sessao-presenca/nova'
      path: '/sessao-presenca/nova'
      fullPath: '/sessao-presenca/nova'
      preLoaderRoute: typeof SessaoPresencaNovaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessao-presenca/$sessaoId': {
      id: '/sessao-presenca/$sessaoId'
      path: '/sessao-presenca/$sessaoId'
      fullPath: '/sessao-presenca/$sessaoId'
      preLoaderRoute: typeof SessaoPresencaSessaoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recebimento/gestao-recursos/': {
      id: '/recebimento/gestao-recursos/'
      path: '/recebimento/gestao-recursos'
      fullPath: '/recebimento/gestao-recursos/'
      preLoaderRoute: typeof RecebimentoGestaoRecursosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SessaoPresencaSessaoIdRoute: SessaoPresencaSessaoIdRoute,
  SessaoPresencaNovaRoute: SessaoPresencaNovaRoute,
  RecebimentoIndexRoute: RecebimentoIndexRoute,
  SessaoPresencaIndexRoute: SessaoPresencaIndexRoute,
  RecebimentoGestaoRecursosIndexRoute: RecebimentoGestaoRecursosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
