import {
  Activity,
  ArrowLeftRight,
  BarChart4,
  ClipboardCheck,
  ClipboardList,
  FileText,
  FileWarning,
  FolderTree,
  HandHeart,
  Headphones,
  LineChart,
  LayoutGrid,
  Map,
  MapPin,
  Monitor,
  Warehouse as WarehouseIcon,
  PlayCircle,
  Printer,
  Package,
  PackageCheck,
  Boxes,
  Container,
  Receipt,
  Shuffle,
  Scale,
  Timer,
  Coffee,
  Truck,
  Forklift,
  Plus,
  CalendarClock,
  Wrench,
  Undo2,
  Warehouse,
  Building2,
  ShieldCheck,
  ScrollText,
  Settings2,
  Scissors,
  ShieldAlert,
  AlertTriangle,
  Users,
  UsersRound,
} from 'lucide-react';

import type { NavGroup } from './sidebar.types';

/**
 * Sidebar navigation — grouped by operational journey (entrada → estoque → saída → rotina → config).
 */
export const sidebarConfig: NavGroup[] = [
  {
    id: 'painel',
    label: 'Painel',
    icon: LineChart,
    defaultOpen: true,
    items: [
      {
        id: 'painel-operacional',
        label: 'Painel Operacional',
        icon: Monitor,
        href: '/dashboard-operacional',
      },
      {
        id: 'indicadores',
        label: 'Indicadores',
        icon: Activity,
        href: '/indicadores',
      },
      {
        id: 'relatorios',
        label: 'Relatórios',
        icon: BarChart4,
        href: '/relatorios',
      },
    ],
  },
  {
    id: 'cadastros-estrutura',
    label: 'Cadastros e Estrutura',
    icon: FolderTree,
    items: [
      {
        id: 'cadastros-infraestrutura',
        label: 'Infraestrutura',
        icon: Building2,
        items: [
          {
            id: 'unidades',
            label: 'Unidades',
            icon: Building2,
            href: '/unidades',
          },
          {
            id: 'produtos',
            label: 'Produtos',
            icon: Package,
            href: '/produtos',
          },
          { id: 'docas', label: 'Docas', icon: Warehouse, href: '/docas' },
          {
            id: 'enderecos',
            label: 'Endereços',
            icon: MapPin,
            href: '/enderecos',
          },
          {
            id: 'produto-enderecos',
            label: 'Produto x Endereço',
            icon: Shuffle,
            href: '/produto-enderecos',
          },
          {
            id: 'armazem-mapa',
            label: 'Mapa do Armazém',
            icon: Warehouse,
            href: '/armazem/mapa',
          },
          {
            id: 'depositos',
            label: 'Depósitos',
            icon: Container,
            href: '/depositos',
          },
        ],
      },
      {
        id: 'cadastros-pessoas',
        label: 'Pessoas e Acessos',
        icon: Users,
        items: [
          {
            id: 'usuarios',
            label: 'Usuários',
            icon: Users,
            href: '/usuarios',
          },
          {
            id: 'funcionarios',
            label: 'Funcionários',
            icon: UsersRound,
            href: '/funcionarios',
          },
          {
            id: 'perfis-permissao',
            label: 'Perfis de Acesso',
            icon: ShieldCheck,
            href: '/usuarios/perfis',
          },
        ],
      },
      {
        id: 'cadastros-frota',
        label: 'Frota',
        icon: Truck,
        items: [
          {
            id: 'frota',
            label: 'Veículos',
            icon: Truck,
            href: '/frota',
          },
          {
            id: 'frota-agenda',
            label: 'Agenda e Alertas',
            icon: CalendarClock,
            href: '/frota/agenda',
          },
          {
            id: 'frota-cadastro',
            label: 'Cadastrar Veículo',
            icon: Plus,
            href: '/frota/novo',
          },
        ],
      },
      {
        id: 'cadastros-equipamento',
        label: 'Equipamentos',
        icon: Forklift,
        items: [
          {
            id: 'equipamento',
            label: 'Equipamentos',
            icon: Forklift,
            href: '/equipamento',
          },
          {
            id: 'equipamento-manutencao',
            label: 'Manutenção',
            icon: Wrench,
            href: '/equipamento/manutencao',
          },
          {
            id: 'equipamento-cadastro',
            label: 'Cadastrar Equipamento',
            icon: Plus,
            href: '/equipamento/novo',
          },
        ],
      },
    ],
  },
  {
    id: 'recebimento',
    label: 'Recebimento',
    icon: PackageCheck,
    items: [
      {
        id: 'recebimento-gestao',
        label: 'Recebimento',
        icon: PackageCheck,
        href: '/recebimento',
      },
      {
        id: 'recebimento-painel',
        label: 'Painel do Dia',
        icon: Monitor,
        href: '/recebimento/painel',
      },
    ],
  },
  {
    id: 'estoque-armazenagem',
    label: 'Estoque e Armazenagem',
    icon: Boxes,
    items: [
      {
        id: 'estoque',
        label: 'Estoque',
        icon: Boxes,
        href: '/estoque',
      },
      {
        id: 'estoque-mapa-ocupacao',
        label: 'Estoque por Posição',
        icon: LayoutGrid,
        href: '/estoque/mapa-ocupacao',
      },
      {
        id: 'inventario',
        label: 'Inventários',
        icon: ClipboardList,
        href: '/inventario',
      },
      {
        id: 'armazenagem',
        label: 'Armazenagem',
        icon: Warehouse,
        href: '/armazenagem',
      },
      {
        id: 'regras-enderecamento',
        label: 'Regras de Endereçamento',
        icon: MapPin,
        href: '/armazenagem/regras-enderecamento',
      },
      {
        id: 'estoque-anomalias',
        label: 'Anomalias de Estoque',
        icon: AlertTriangle,
        items: [
          {
            id: 'cnc',
            label: 'CNC',
            icon: ShieldAlert,
            href: '/cnc',
          },
          {
            id: 'debito-transportadora',
            label: 'Débito Transportadora',
            icon: FileWarning,
            href: '/debito-transportadora',
          },
          {
            id: 'divergencia-estoque',
            label: 'Divergência de Estoque',
            icon: ClipboardList,
            href: '/estoque/divergencias',
          },
        ],
      },
      {
        id: 'aprovacao-movimentacao',
        label: 'Aprovações de Estoque',
        icon: ClipboardCheck,
        href: '/aprovacao-movimentacao',
      },
      {
        id: 'wms-operacoes',
        label: 'Operações WMS',
        icon: WarehouseIcon,
        items: [
          {
            id: 'op-wms-dashboard',
            label: 'Painel do Operador',
            icon: Monitor,
            href: '/op-wms',
          },
          {
            id: 'op-wms-ressuprimento',
            label: 'Ressuprimento',
            icon: PackageCheck,
            href: '/op-wms/ressuprimento',
          },
          {
            id: 'op-wms-gestao-picking',
            label: 'Gestão de Picking',
            icon: ClipboardList,
            href: '/op-wms/gestao-picking',
          },
          {
            id: 'op-wms-gestao-recursos',
            label: 'Gestão de Recursos',
            icon: Activity,
            href: '/op-wms/gestao-recursos',
          },
          {
            id: 'op-wms-distribuicao-demandas',
            label: 'Planejamento de Demandas',
            icon: Shuffle,
            href: '/op-wms/distribuicao-demandas',
          },
          {
            id: 'op-wms-regras',
            label: 'Regras WMS',
            icon: ScrollText,
            href: '/regras-wms',
          },
        ],
      },
    ],
  },
  {
    id: 'devolucao',
    label: 'Devoluções',
    icon: Undo2,
    items: [
      {
        id: 'devolucao-gestao',
        label: 'Gestão de Demandas',
        icon: Undo2,
        href: '/devolucao',
      },
      {
        id: 'devolucao-relatorios',
        label: 'Relatórios',
        icon: BarChart4,
        href: '/devolucao/relatorios',
      },
    ],
  },
  {
    id: 'expedicao-transporte',
    label: 'Expedição e Transporte',
    icon: Container,
    items: [
      {
        id: 'expedicao',
        label: 'Expedição',
        icon: PackageCheck,
        items: [
          {
            id: 'torre-controle-expedicao',
            label: 'Torre de Controle',
            icon: Monitor,
            href: '/expedicao/torre-controle',
          },
          {
            id: 'corte-operacional',
            label: 'Corte Operacional',
            icon: Scissors,
            href: '/expedicao/corte-operacional',
          },
          {
            id: 'clientes-especiais',
            label: 'Clientes Especiais',
            icon: AlertTriangle,
            href: '/expedicao/clientes-especiais',
          },
          {
            id: 'peso-variavel',
            label: 'Peso Variável',
            icon: Scale,
            href: '/peso-variavel',
          },
        ],
      },
      {
        id: 'transporte',
        label: 'Transporte',
        icon: Truck,
        items: [
          {
            id: 'transporte-alocacao',
            label: 'Alocação de Cargas',
            icon: Container,
            href: '/transporte',
          },
          {
            id: 'transporte-transportadoras',
            label: 'Transportadoras',
            icon: Building2,
            href: '/transporte/transportadoras',
          },
          {
            id: 'transporte-placas',
            label: 'Placas',
            icon: Truck,
            href: '/transporte/placas',
          },
          {
            id: 'transporte-impressao-mapa-separacao',
            label: 'Geração de Mapas',
            icon: Printer,
            href: '/transporte/impressao-mapa-separacao',
          },
          {
            id: 'transporte-portal',
            label: 'Portal Transportador',
            icon: Truck,
            href: '/transporte/portal',
          },
          {
            id: 'transporte-custos',
            label: 'Custos de Frete',
            icon: Receipt,
            href: '/transporte/custos-frete',
          },
          {
            id: 'transporte-custos-dashboard',
            label: 'Painel de Frete',
            icon: BarChart4,
            href: '/transporte/custos-frete/dashboard',
          },
          {
            id: 'transporte-perfis-tarifas',
            label: 'Perfis e Tarifas',
            icon: Settings2,
            href: '/transporte/perfis-tarifas',
          },
        ],
      },
    ],
  },
  {
    id: 'rotina-operacional',
    label: 'Rotina Operacional',
    icon: CalendarClock,
    items: [
      {
        id: 'sessao-operacao-sessoes',
        label: 'Sessões de Trabalho',
        icon: ClipboardList,
        href: '/sessao-operacao/sessoes',
      },
      {
        id: 'sessao-operacao-nova',
        label: 'Nova Sessão',
        icon: Plus,
        href: '/sessao-operacao/sessoes/nova',
      },
      {
        id: 'sessao-operacao-escalas',
        label: 'Escalas',
        icon: Timer,
        href: '/sessao-operacao/escalas',
      },
      {
        id: 'pausas',
        label: 'Pausas',
        icon: Timer,
        items: [
          {
            id: 'pausas-monitor',
            label: 'Monitor de Pausas',
            icon: Monitor,
            href: '/pausas',
          },
          {
            id: 'pausas-registro',
            label: 'Registrar Pausa',
            icon: PlayCircle,
            href: '/pausas/registro',
          },
          {
            id: 'pausas-relatorios',
            label: 'Relatórios',
            icon: BarChart4,
            href: '/pausas/relatorios',
          },
        ],
      },
      {
        id: 'passagem-bastao',
        label: 'Passagem de Turno',
        icon: ArrowLeftRight,
        items: [
          {
            id: 'passagem-bastao-relatorios',
            label: 'Relatórios',
            icon: BarChart4,
            href: '/passagem-bastao/relatorios',
          },
        ],
      },
    ],
  },
  {
    id: 'configuracoes',
    label: 'Configurações',
    icon: Settings2,
    items: [
      {
        id: 'config-operacional-hub',
        label: 'Parâmetros',
        icon: Settings2,
        href: '/config-operacional',
      },
      {
        id: 'regras-produtividade',
        label: 'Regras de Produtividade',
        icon: Timer,
        href: '/config-operacional/regras-produtividade',
      },
      {
        id: 'regras-pausas',
        label: 'Regras de Pausa',
        icon: Coffee,
        href: '/config-operacional/regras-pausas',
      },
      {
        id: 'config-mapa',
        label: 'Configuração de Mapa',
        icon: Map,
        href: '/expedicao/config-mapa',
      },
      {
        id: 'config-impressao',
        label: 'Configuração de Impressão',
        icon: Printer,
        href: '/expedicao/config-impressao',
      },
    ],
  },
  {
    id: 'gestao',
    label: 'Gestão',
    icon: Receipt,
    items: [
      {
        id: 'financeiro',
        label: 'Financeiro',
        icon: Receipt,
        href: '/financeiro',
      },
    ],
  },
  {
    id: 'suporte',
    label: 'Suporte',
    icon: HandHeart,
    items: [
      {
        id: 'suporte',
        label: 'Central de Suporte',
        icon: Headphones,
        href: '/suporte',
      },
      {
        id: 'documentacao',
        label: 'Documentação',
        icon: FileText,
        href: '/documentacao',
      },
    ],
  },
];
