import {
  Activity,
  ArrowLeftRight,
  BarChart4,
  ClipboardCheck,
  ClipboardList,
  FileText,
  FileWarning,
  FolderTree,
  HandHeart,
  Headphones,
  LineChart,
  LayoutGrid,
  Map,
  MapPin,
  Monitor,
  Network,
  PenTool,
  Warehouse as WarehouseIcon,
  PlayCircle,
  Printer,
  Package,
  PackageCheck,
  Boxes,
  Container,
  Receipt,
  Shuffle,
  Scale,
  Timer,
  Coffee,
  Truck,
  Forklift,
  Plus,
  CalendarClock,
  Wrench,
  Undo2,
  Warehouse,
  Building2,
  ShieldCheck,
  ScrollText,
  Settings2,
  Scissors,
  AlertTriangle,
  Users,
  UsersRound,
} from 'lucide-react';

import type { NavGroup } from './sidebar.types';

/**
 * Sidebar navigation definition — edit this file to add/remove groups and routes.
 */
export const sidebarConfig: NavGroup[] = [
  {
    id: 'operacional',
    label: 'Operacional',
    icon: Network,
    items: [
      {
        id: 'dashboard-operacional',
        label: 'Dashboard Operacional',
        icon: LineChart,
        href: '/dashboard-operacional',
      },
      {
        id: 'cadastros-base',
        label: 'Cadastros',
        icon: FolderTree,
        defaultOpen: true,
        items: [
          {
            id: 'cadastros-infraestrutura',
            label: 'Infraestrutura',
            icon: Building2,
            items: [
              {
                id: 'unidades',
                label: 'Unidades',
                icon: Building2,
                href: '/unidades',
              },
              {
                id: 'produtos',
                label: 'Produtos',
                icon: Package,
                href: '/produtos',
              },
              { id: 'docas', label: 'Docas', icon: Warehouse, href: '/docas' },
              {
                id: 'enderecos',
                label: 'Endereços',
                icon: MapPin,
                href: '/enderecos',
              },
              {
                id: 'produto-enderecos',
                label: 'Slotting',
                icon: Shuffle,
                href: '/produto-enderecos',
              },
              {
                id: 'armazem-mapa',
                label: 'Mapa do Armazém',
                icon: Warehouse,
                href: '/armazem/mapa',
              },
            ],
          },
          {
            id: 'cadastros-pessoas',
            label: 'Pessoas e acesso',
            icon: Users,
            items: [
              {
                id: 'usuarios',
                label: 'Usuários',
                icon: Users,
                href: '/usuarios',
              },
              {
                id: 'funcionarios',
                label: 'Funcionários',
                icon: UsersRound,
                href: '/funcionarios',
              },
              {
                id: 'perfis-permissao',
                label: 'Perfis e Permissões',
                icon: ShieldCheck,
                href: '/usuarios/perfis',
              },
            ],
          },
          {
            id: 'cadastros-frota',
            label: 'Frota',
            icon: Truck,
            items: [
              {
                id: 'frota',
                label: 'Diretório de frota',
                icon: Truck,
                href: '/frota',
              },
              {
                id: 'frota-agenda',
                label: 'Agenda e alertas',
                icon: CalendarClock,
                href: '/frota/agenda',
              },
              {
                id: 'frota-cadastro',
                label: 'Cadastrar veículo',
                icon: Plus,
                href: '/frota/novo',
              },
            ],
          },
          {
            id: 'cadastros-equipamento',
            label: 'Equipamentos',
            icon: Forklift,
            items: [
              {
                id: 'equipamento',
                label: 'Diretório de ativos',
                icon: Forklift,
                href: '/equipamento',
              },
              {
                id: 'equipamento-manutencao',
                label: 'Manutenção',
                icon: Wrench,
                href: '/equipamento/manutencao',
              },
              {
                id: 'equipamento-cadastro',
                label: 'Cadastrar equipamento',
                icon: Plus,
                href: '/equipamento/novo',
              },
            ],
          },
        ],
      },
      {
        id: 'estoque',
        label: 'Estoque',
        icon: Boxes,
        items: [
          {
            id: 'inventario',
            label: 'Inventário',
            icon: ClipboardList,
            href: '/inventario',
          },
          {
            id: 'armazenagem',
            label: 'Armazenagem',
            icon: Warehouse,
            href: '/armazenagem',
          },
          {
            id: 'debito-transportadora',
            label: 'Débitos',
            icon: FileWarning,
            href: '/debito-transportadora',
          },
          {
            id: 'aprovacao-movimentacao',
            label: 'Aprovação de Movimentações',
            icon: ClipboardCheck,
            href: '/aprovacao-movimentacao',
          },
        ],
      },
      {
        id: 'devolucao',
        label: 'Devolução',
        icon: Undo2,
        defaultOpen: true,
        items: [
          {
            id: 'devolucao-gestao',
            label: 'Gestão de Demandas',
            icon: Undo2,
            href: '/devolucao',
          },
          {
            id: 'devolucao-relatorios',
            label: 'Relatórios',
            icon: BarChart4,
            href: '/devolucao/relatorios',
          },
        ],
      },
      {
        id: 'pausas',
        label: 'Pausas',
        icon: Timer,
        defaultOpen: true,
        items: [
          {
            id: 'pausas-monitor',
            label: 'Monitor ao Vivo',
            icon: Monitor,
            href: '/pausas',
          },
          {
            id: 'pausas-registro',
            label: 'Registrar Pausa',
            icon: PlayCircle,
            href: '/pausas/registro',
          },
          {
            id: 'pausas-relatorios',
            label: 'Relatórios',
            icon: BarChart4,
            href: '/pausas/relatorios',
          },
        ],
      },
      {
        id: 'passagem-bastao',
        label: 'Passagem de Bastão',
        icon: ArrowLeftRight,
        defaultOpen: true,
        items: [
          {
            id: 'passagem-bastao-relatorios',
            label: 'Relatórios',
            icon: BarChart4,
            href: '/passagem-bastao/relatorios',
          },
        ],
      },
      {
        id: 'expedicao',
        label: 'Expedição',
        icon: PackageCheck,
        defaultOpen: true,
        items: [
          {
            id: 'torre-controle-expedicao',
            label: 'Torre de Controle',
            icon: Monitor,
            href: '/expedicao/torre-controle',
          },
          {
            id: 'corte-operacional',
            label: 'Corte Operacional',
            icon: Scissors,
            href: '/expedicao/corte-operacional',
          },
          {
            id: 'clientes-especiais',
            label: 'Clientes Especiais',
            icon: AlertTriangle,
            href: '/expedicao/clientes-especiais',
          },
          {
            id: 'config-mapa',
            label: 'Config. Mapa',
            icon: Map,
            href: '/expedicao/config-mapa',
          },
          {
            id: 'config-impressao',
            label: 'Config. Impressão',
            icon: Printer,
            href: '/expedicao/config-impressao',
          },
          {
            id: 'peso-variavel',
            label: 'Peso Variável',
            icon: Scale,
            href: '/peso-variavel',
          },
        ],
      },
      {
        id: 'config-operacional',
        label: 'Configurações',
        icon: Settings2,
        items: [
          {
            id: 'config-operacional-hub',
            label: 'Visão geral',
            icon: Settings2,
            href: '/config-operacional',
          },
          {
            id: 'regras-produtividade',
            label: 'Regras de Produtividade',
            icon: Timer,
            href: '/config-operacional/regras-produtividade',
          },
          {
            id: 'regras-pausas',
            label: 'Regras de Pausa',
            icon: Coffee,
            href: '/config-operacional/regras-pausas',
          },
        ],
      },
      {
        id: 'transporte',
        label: 'Transporte',
        icon: Container,
        defaultOpen: false,
        items: [
          {
            id: 'transporte-alocacao',
            label: 'Expedição de Cargas',
            icon: Container,
            href: '/transporte',
          },
          {
            id: 'transporte-transportadoras',
            label: 'Transportadoras',
            icon: Building2,
            href: '/transporte/transportadoras',
          },
          {
            id: 'transporte-placas',
            label: 'Placas',
            icon: Truck,
            href: '/transporte/placas',
          },
          {
            id: 'transporte-impressao-mapa-separacao',
            label: 'Geração de Mapas',
            icon: Printer,
            href: '/transporte/impressao-mapa-separacao',
          },
          {
            id: 'transporte-portal',
            label: 'Portal Transportador',
            icon: Truck,
            href: '/transporte/portal',
          },
          {
            id: 'transporte-custos',
            label: 'Gestão de Frete',
            icon: Receipt,
            href: '/transporte/custos-frete',
          },
          {
            id: 'transporte-custos-dashboard',
            label: 'Dashboard de Frete',
            icon: BarChart4,
            href: '/transporte/custos-frete/dashboard',
          },
          {
            id: 'transporte-perfis-tarifas',
            label: 'Perfis & Tarifas',
            icon: Settings2,
            href: '/transporte/perfis-tarifas',
          },
        ],
      },
      {
        id: 'recebimento',
        label: 'Recebimento',
        icon: Truck,
        href: '/recebimento',
      },
      {
        id: 'op-wms',
        label: 'Operações WMS',
        icon: WarehouseIcon,
        defaultOpen: true,
        items: [
          {
            id: 'op-wms-dashboard',
            label: 'Painel do Operador',
            icon: Monitor,
            href: '/op-wms',
          },
          {
            id: 'op-wms-ressuprimento',
            label: 'Ressuprimento',
            icon: PackageCheck,
            href: '/op-wms/ressuprimento',
          },
          {
            id: 'op-wms-gestao-picking',
            label: 'Gestão de Picking',
            icon: ClipboardList,
            href: '/op-wms/gestao-picking',
          },
          {
            id: 'op-wms-gestao-recursos',
            label: 'Gestão de Recursos',
            icon: Activity,
            href: '/op-wms/gestao-recursos',
          },
          {
            id: 'op-wms-distribuicao-demandas',
            label: 'Distribuição de Demandas',
            icon: Shuffle,
            href: '/op-wms/distribuicao-demandas',
          },
          {
            id: 'op-wms-regras',
            label: 'Regras WMS',
            icon: ScrollText,
            href: '/regras-wms',
          },
        ],
      },
      {
        id: 'layout-cd',
        label: 'Layout CD',
        icon: LayoutGrid,
        items: [
          {
            id: 'layout-cd-projeto',
            label: 'Novo Projeto',
            icon: PenTool,
            href: '/layout-cd',
          },
          {
            id: 'layout-cd-construtor',
            label: 'Construtor',
            icon: LayoutGrid,
            href: '/layout-cd/construtor',
          },
          {
            id: 'layout-cd-armazem',
            label: 'Armazém',
            icon: WarehouseIcon,
            href: '/layout-cd/armazem',
          },
        ],
      },
    ],
  },
  {
    id: 'sessao-operacao',
    label: 'Sessão Operação',
    icon: CalendarClock,
    defaultOpen: true,
    items: [
      {
        id: 'sessao-operacao-sessoes',
        label: 'Sessões de Trabalho',
        icon: ClipboardList,
        href: '/sessao-operacao/sessoes',
      },
      {
        id: 'sessao-operacao-nova',
        label: 'Nova Sessão',
        icon: Plus,
        href: '/sessao-operacao/sessoes/nova',
      },
      {
        id: 'sessao-operacao-escalas',
        label: 'Escalas',
        icon: Timer,
        href: '/sessao-operacao/escalas',
      },
    ],
  },
  {
    id: 'gestao',
    label: 'Gestão',
    icon: LineChart,
    items: [
      { id: 'financeiro', label: 'Financeiro', icon: Receipt, href: '/financeiro' },
      { id: 'relatorios', label: 'Relatórios', icon: BarChart4, href: '/relatorios' },
      {
        id: 'indicadores',
        label: 'Indicadores',
        icon: Monitor,
        href: '/indicadores',
      },
    ],
  },
  {
    id: 'apoio',
    label: 'Apoio',
    icon: HandHeart,
    items: [
      {
        id: 'suporte',
        label: 'Suporte',
        icon: Headphones,
        href: '/suporte',
      },
      {
        id: 'documentacao',
        label: 'Documentação',
        icon: FileText,
        href: '/documentacao',
      },
    ],
  },
];
